### ISSUE TITLE
Update error on Windows Dev Drive: The system cannot move the file to a different disk drive

### ISSUE THREAD

**Issue by ThatOtherAndrew** [axodotdev/axoupdater#120]
Forwarding from https://github.com/astral-sh/uv/issues/3845, as I was informed by a member of Astral (@charliermarsh) that this is likely a problem with `axoupdater`:

> I am using a [Dev Drive](https://learn.microsoft.com/en-us/windows/dev-drive/) on Windows 11, mounted at `D:`. As recommended by Microsoft docs, I have mapped CARGO_HOME to this drive to improve cache speeds. This seems to cause issues with `uv self update` however, resulting in the following error:
> 
> ```
> uv self update
> info: Checking for updates...
> error: The system cannot move the file to a different disk drive. (os error 17)
> [Exit code 2]
> ```
> 
> The issue was reproduced on `uv` version 0.2.3, one older than the current version. The issue cannot be reproduced on the latest v0.2.4 as `uv self update` exits early upon detecting being on the latest version, however I am making the assumption that the issue is still present.

**Comment by mistydemeo** [comment]
Interesting! Thanks for the heads up. I'll review and see where this might be coming from.

**Comment by mistydemeo** [comment]
I see where the problem is. I've developed a fix; it'll take me a bit of time to confirm that it works as expected and to get a new axoupdater release, but I'll notify you when it's ready.

**Comment by mistydemeo** [comment]
All right, thinking about it again - we were renaming the binary in the first place because Windows doesn't permit overwriting a running executable. Likewise, Windows doesn't allow *deleting* a running executable. That means an approach of moving an executable via copy-and-delete (`MoveFileExA` with `MOVEFILE_COPY_ALLOWED`) also won't work.

It may be safer to switch temporary directory libraries so we can situate the temporary directory inside the install prefix, where we can be pretty confident it'll be on the same filesystem.

**Comment by ThatOtherAndrew** [comment]
Thanks for the ultra-quick response! I'm not too familiar with the underlying filesystem mechanics so unfortunately am not able to help, but I'll keep my eyes peeled.

**Comment by mistydemeo** [comment]
Opened a PR with a probable fix - #121. I'm the only one in the office today due to the US holiday, so it'll likely be a day or two until we have the chance to review/test/release.
