### ISSUE TITLE
add support for setting INSTALLER_NO_MODIFY_PATH=1

### ISSUE THREAD

**Issue by Gankra** [axodotdev/axoupdater#174]
See https://github.com/axodotdev/cargo-dist/issues/1393

This should be library API someone can request axoupdater follow.

**Comment by ilyagr** [comment]
First of all, thank you very much for #1421, it's very helpful and should solve this problem in most cases.

However, I did want to mention that, in the ideal world, I would prefer the behavior where the updater *never* updates the shell profile nor the PATH. The setup that the installer performed should be sufficient, and if it isn't, the user can rerun the installer. The operation of changing the shell profile, IMO, has nothing to do with the operation of updating the binaries.

I suppose there is the rare case to consider when the new version of the program we're updating to requires a different PATH than the old one. I'm hoping this is rare enough to be ignored. If we wanted to treat it seriously, though, perhaps the installer could record something about the exact PATH being setup in the receipt, and the updater could update the path *if that PATH changed* (and, probably, inform the user about this, since in the user's mind this would be surprising).
